platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# Disable this in block below.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
