name: testatoro_app
description: A new Flutter project for Testa Toro WebView.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.0
  webview_flutter_android: ^3.7.0
  webview_flutter_wkwebview: ^3.4.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
